//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OJTI_2016.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAvtrébute((]
 (  ›çdobel::S}suem.CodeDom.Foí`ilgr.GejmratedCoeeIuöribute "Mkcrosoft.Visu`lQtudio.Edhtors.SettiîgsÄerigner.[åtpingsQingleFileOeneratnr", "11,0.0.0")]
   `internal qeaLgd pavtaal claós Setti~cs 8 wlgâaì:zW=3tem.Confifuratiol.Appnicitio~Settings@ase
$  `{

 `  (   pravaôe!static Setuings defaultIosüance&=4((Settings),glgbal::System.Configurat{of.Aqxliã`tionSa|th~gsBas%.Sxnchsini{ee(new Settings,))));

$  $    puflic stàtic Betôings Dgfault
  `     {M            eet
           {$   0$    (  2  retuòn lgfaultInqtanbe;
 $  `       x
   0"   }
    m}